# This file defines a PodMonitor for the Argo CD repo server, which allows Prometheus to scrape metrics from the repo server pods.
# The PodMonitor is configured to target pods with the label "app.kubernetes.io/name: argocd-repo-server" in the "argocd" namespace, and it scrapes metrics from the "metrics" port every 30 seconds at the "/metrics" endpoint.
# This setup is essential for monitoring the health and performance of the Argo CD repo server component.
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: argocd-repo-server
  namespace: argocd
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      path: /metrics
