# Service Monitors is a custom resource definition (CRD) in Kubernetes that allows you to define how to monitor services running in your cluster.
# It is commonly used with Prometheus to specify which services should be scraped for metrics and how to scrape them.

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-metrics
  namespace: argocd
  labels:
    release: kube-prometheus-stack # must match prometheusSpec.serviceMonitorSelector
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-metrics # matches the argocd-metrics Service
  endpoints:
    - port: metrics # port name on the argocd-metrics Service (8082)
      interval: 30s
      path: /metrics
