# What does argocd repo server metrics scrape?
# It scrapes the metrics from the argocd-repo-server component of Argo CD, which is responsible for managing the Git repositories that Argo CD uses to deploy applications.
# The metrics collected from the argocd-repo-server can include information about the health and performance of the repository server, as well as details about the Git repositories being managed by Argo CD.
# These metrics can be used for monitoring and troubleshooting purposes, allowing administrators to gain insights into the behavior of their Argo CD deployment and ensure that it is running smoothly.

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-repo-server
  namespace: argocd
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  endpoints:
    - port: metrics # port name on the argocd-repo-server Service (8084)
      interval: 30s
      path: /metrics
