apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: backend-external-secret
  namespace: proshop
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager-dev # prod: aws-secrets-manager-prod
    kind: ClusterSecretStore
  target:
    name: backend-secrets
    creationPolicy: Owner
  data:
    - secretKey: PORT
      remoteRef:
        key: proshop/backend # prod: proshop/backend-prod
        property: PORT
    - secretKey: MONGO_URI
      remoteRef:
        key: proshop/backend # prod: proshop/backend-prod
        property: MONGO_URI
    - secretKey: JWT_SECRET
      remoteRef:
        key: proshop/backend # prod: proshop/backend-prod
        property: JWT_SECRET
    - secretKey: PAYPAL_CLIENT_ID
      remoteRef:
        key: proshop/backend # prod: proshop/backend-prod
        property: PAYPAL_CLIENT_ID
    - secretKey: PAYPAL_APP_SECRET
      remoteRef:
        key: proshop/backend # prod: proshop/backend-prod
        property: PAYPAL_APP_SECRET
    - secretKey: PAYPAL_API_URL
      remoteRef:
        key: proshop/backend # prod: proshop/backend-prod
        property: PAYPAL_API_URL
    - secretKey: PAGINATION_LIMIT
      remoteRef:
        key: proshop/backend # prod: proshop/backend-prod
        property: PAGINATION_LIMIT
    - secretKey: NODE_ENV
      remoteRef:
        key: proshop/backend # prod: proshop/backend-prod
        property: NODE_ENV
