apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-smtp-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager-dev
    kind: ClusterSecretStore
  target:
    name: alertmanager-smtp-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        alertmanager.yaml: |
          global:
            resolve_timeout: 5m
            smtp_smarthost: "smtp.gmail.com:587"
            smtp_from: "alertmanager@proshop-eks-dev"
            smtp_auth_username: "{{ .username }}"
            smtp_auth_password: "{{ .password }}"
            smtp_require_tls: true
          route:
            group_by:
              - alertname
              - namespace
            group_wait: 30s
            group_interval: 5m
            repeat_interval: 12h
            receiver: email-notifications
          receivers:
            - name: email-notifications
              email_configs:
                - to: "{{ .username }}"
                  send_resolved: true
          inhibit_rules:
            - source_matchers:
                - severity="critical"
              target_matchers:
                - severity="warning"
              equal:
                - alertname
                - namespace
  data:
    - secretKey: username
      remoteRef:
        key: proshop/backend
        property: alertmanager_smtp_username
    - secretKey: password
      remoteRef:
        key: proshop/backend
        property: alertmanager_smtp_password
