apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager-dev
    kind: ClusterSecretStore
  target:
    name: backend-secret
    creationPolicy: Owner
  data:
    - secretKey: grafana_username
      remoteRef:
        key: proshop/backend
        property: grafana_username
    - secretKey: grafana_password
      remoteRef:
        key: proshop/backend
        property: grafana_password
