apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-servicemonitors
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kalpit10/cloud-native-ecommerce-platform.git
    targetRevision: phase1-test
    path: gitops/argocd/servicemonitors
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false # argocd namespace already exists
